/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Model.ConnectionProvider;
import net.proteanit.sql.DbUtils;
import java.util.Date;

/**
 *
 * @author Acer
 */
public class library extends javax.swing.JFrame {

    /**
     * Creates new form library
     */
    public library() {
        initComponents();
        dateLabel();
    }
    public void dateLabel() {
        // Get the current date and format it
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        Date date = new Date();
        String dateString = formatter.format(date);

        // Set the formatted date as the text of the label
        dateLabel.setText(dateString);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bookIdText = new javax.swing.JTextField();
        bookNameText = new javax.swing.JTextField();
        bookAuthorText = new javax.swing.JTextField();
        bookYearText = new javax.swing.JTextField();
        addBook = new javax.swing.JButton();
        bookUpdate = new javax.swing.JButton();
        bookDelete = new javax.swing.JButton();
        clearBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        memberIdText = new javax.swing.JTextField();
        memberLastNameText = new javax.swing.JTextField();
        memberFirstNameText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        addMember = new javax.swing.JButton();
        memberUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        memberClear = new javax.swing.JButton();
        memberSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bookIdText1 = new javax.swing.JTextField();
        memberIdText2 = new javax.swing.JTextField();
        issueDateText = new com.toedter.calendar.JDateChooser();
        dueDateText = new com.toedter.calendar.JDateChooser();
        issueBookButton = new javax.swing.JButton();
        clearIssue = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        memberIdText3 = new javax.swing.JTextField();
        bookIdText3 = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        returnBookButton = new javax.swing.JButton();
        clearReturn = new javax.swing.JButton();
        dueDateText1 = new javax.swing.JTextField();
        issueDateText1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel10.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel10.setText("Member ID");

        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel11.setText("Member ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel8.setText("Book ID");

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel9.setText("Book Name");

        jLabel12.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel12.setText("Year");

        jLabel13.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel13.setText("Author");

        bookIdText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        bookNameText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        bookAuthorText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        bookYearText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        addBook.setBackground(new java.awt.Color(102, 204, 0));
        addBook.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        addBook.setForeground(new java.awt.Color(255, 255, 255));
        addBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        addBook.setText("ADD");
        addBook.setFocusable(false);
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        bookUpdate.setBackground(new java.awt.Color(0, 102, 255));
        bookUpdate.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        bookUpdate.setForeground(new java.awt.Color(255, 255, 255));
        bookUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/update.png"))); // NOI18N
        bookUpdate.setText("UPDATE");
        bookUpdate.setFocusable(false);
        bookUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookUpdateActionPerformed(evt);
            }
        });

        bookDelete.setBackground(new java.awt.Color(255, 51, 51));
        bookDelete.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        bookDelete.setForeground(new java.awt.Color(255, 255, 255));
        bookDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        bookDelete.setText("DELETE");
        bookDelete.setFocusable(false);
        bookDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDeleteActionPerformed(evt);
            }
        });

        clearBook.setBackground(new java.awt.Color(255, 153, 0));
        clearBook.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        clearBook.setForeground(new java.awt.Color(255, 255, 255));
        clearBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/clear.png"))); // NOI18N
        clearBook.setText("CLEAR");
        clearBook.setFocusable(false);
        clearBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBookActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/search.png"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bookNameText)
                        .addComponent(bookAuthorText)
                        .addComponent(bookYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bookIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bookUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bookDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBook, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(bookIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bookNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(bookAuthorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bookYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );

        jTabbedPane1.addTab("Books", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel2.setText("Member ID");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("Adderss");

        memberIdText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        memberLastNameText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        memberLastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberLastNameTextActionPerformed(evt);
            }
        });

        memberFirstNameText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        memberFirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberFirstNameTextActionPerformed(evt);
            }
        });

        addressText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });

        addMember.setBackground(new java.awt.Color(102, 204, 0));
        addMember.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        addMember.setForeground(new java.awt.Color(255, 255, 255));
        addMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        addMember.setText("ADD");
        addMember.setFocusable(false);
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        memberUpdate.setBackground(new java.awt.Color(0, 102, 255));
        memberUpdate.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        memberUpdate.setForeground(new java.awt.Color(255, 255, 255));
        memberUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/update.png"))); // NOI18N
        memberUpdate.setText("UPDATE");
        memberUpdate.setFocusable(false);
        memberUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberUpdateActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        memberClear.setBackground(new java.awt.Color(255, 153, 0));
        memberClear.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        memberClear.setForeground(new java.awt.Color(255, 255, 255));
        memberClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/clear.png"))); // NOI18N
        memberClear.setText("CLEAR");
        memberClear.setFocusable(false);
        memberClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberClearActionPerformed(evt);
            }
        });

        memberSearch.setBackground(new java.awt.Color(51, 51, 51));
        memberSearch.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        memberSearch.setForeground(new java.awt.Color(255, 255, 255));
        memberSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/search.png"))); // NOI18N
        memberSearch.setText("SEARCH");
        memberSearch.setFocusable(false);
        memberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memberUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(memberLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(memberFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memberIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memberSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberClear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(memberFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberClear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );

        jTabbedPane1.addTab("Members", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jLabel14.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel14.setText("Book ID");

        jLabel15.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel15.setText("Issue Date");

        jLabel16.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel16.setText("Member ID");

        jLabel17.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel17.setText("Due Date");

        bookIdText1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        memberIdText2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        issueDateText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        dueDateText.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        issueBookButton.setBackground(new java.awt.Color(0, 153, 255));
        issueBookButton.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        issueBookButton.setForeground(new java.awt.Color(255, 255, 255));
        issueBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/borrow.png"))); // NOI18N
        issueBookButton.setText("ISSUE BOOK");
        issueBookButton.setFocusable(false);
        issueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookButtonActionPerformed(evt);
            }
        });

        clearIssue.setBackground(new java.awt.Color(255, 153, 0));
        clearIssue.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        clearIssue.setForeground(new java.awt.Color(255, 255, 255));
        clearIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/clear.png"))); // NOI18N
        clearIssue.setText("CLEAR");
        clearIssue.setFocusable(false);
        clearIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearIssueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(52, 52, 52)
                        .addComponent(bookIdText1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberIdText2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(issueDateText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dueDateText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(issueBookButton, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(197, 197, 197))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bookIdText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(memberIdText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(issueDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(dueDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(issueBookButton))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Issue Books", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));

        jLabel18.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel18.setText("Book ID");

        jLabel19.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel19.setText("Issue Date");

        jLabel20.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel20.setText("Member ID");

        jLabel21.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel21.setText("Due Date");

        memberIdText3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        bookIdText3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        searchButton.setBackground(new java.awt.Color(51, 51, 51));
        searchButton.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/search.png"))); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.setFocusable(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        returnBookButton.setBackground(new java.awt.Color(255, 51, 51));
        returnBookButton.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        returnBookButton.setForeground(new java.awt.Color(255, 255, 255));
        returnBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/replay_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20 (1).png"))); // NOI18N
        returnBookButton.setText("RETURN BOOK");
        returnBookButton.setFocusable(false);
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        clearReturn.setBackground(new java.awt.Color(255, 153, 0));
        clearReturn.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        clearReturn.setForeground(new java.awt.Color(255, 255, 255));
        clearReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/clear.png"))); // NOI18N
        clearReturn.setText("CLEAR");
        clearReturn.setFocusable(false);
        clearReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearReturnActionPerformed(evt);
            }
        });

        dueDateText1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        issueDateText1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(56, 56, 56)
                        .addComponent(bookIdText3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberIdText3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(issueDateText1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dueDateText1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnBookButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(clearReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookIdText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberIdText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(issueDateText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dueDateText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(163, 163, 163))
        );

        jTabbedPane1.addTab("Return Books", jPanel4);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo2.png"))); // NOI18N
        jLabel1.setText("Nanathari Library");

        jLabel22.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/account_circle_16dp_00000_FILL0_wght400_GRAD0_opsz20 (1).png"))); // NOI18N
        jLabel22.setText("Admin");

        dateLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        dateLabel.setText("jLabel23");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        // TODO add your handling code here:
        String bookId = bookIdText3.getText();
        String memberId = memberIdText3.getText();
        if(bookId.isEmpty()|| memberId.isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields must be filled");
            return;
        }
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("update issue set returnBook='yes'where memberId='"+memberId+"'and bookId='"+bookId+"'");
            JOptionPane.showMessageDialog(null, "book successfully returned");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_returnBookButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String bookId = bookIdText3.getText();
        String memberId = memberIdText3.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from issue where bookId='"+bookId+"'and memberId='"+memberId+"'");
            if(rs.next()){
                issueDateText1.setText(rs.getString(3));
                dueDateText1.setText(rs.getString(4));
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect memberId or bookId");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "connection error");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        String bookId = bookIdText1.getText();
        String memberId = memberIdText2.getText();
        String issueDate = dFormat.format(issueDateText.getDate());
        String dueDate = dFormat.format(dueDateText.getDate());
        String returnBook = "no";
        if(bookId.isEmpty()||memberId.isEmpty()||issueDate.isEmpty()||dueDate.isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields must be filled");
            return;
        }
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from book where bookId='"+bookId+"'");
            if(rs.next()){
                ResultSet rs1 = st.executeQuery("select * from member where memberId='"+memberId+"'");
                if(rs1.next()){
                    st.executeUpdate("insert into issue values('"+bookId+"','"+memberId+"','"+issueDate+"','"+dueDate+"','"+returnBook+"')");
                    JOptionPane.showMessageDialog(null, "Book successfully issued");
                }else{
                    JOptionPane.showMessageDialog(null, "Incorrect memberId");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect BookId");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_issueBookButtonActionPerformed

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        String memberId = memberIdText.getText();
        String memberFirstName = memberFirstNameText.getText();
        String memberLastName = memberLastNameText.getText();
        String memberAddress = addressText.getText();
        if(memberId.isEmpty()||memberFirstName.isEmpty()||memberLastName.isEmpty()||memberAddress.isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields must be filled");
            return;
        }
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into member values('"+memberId+"','"+memberFirstName+"','"+memberLastName+"','"+memberAddress+"')");
            JOptionPane.showMessageDialog(null, "Member successfully added");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Member Id already exists");
        }
    }//GEN-LAST:event_addMemberActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void memberFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberFirstNameTextActionPerformed

    private void memberLastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberLastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberLastNameTextActionPerformed

    private void clearBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBookActionPerformed
        // TODO add your handling code here:
        bookIdText.setText("");
        bookNameText.setText("");
        bookAuthorText.setText("");
        bookYearText.setText("");
    }//GEN-LAST:event_clearBookActionPerformed

    private void bookDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDeleteActionPerformed
        // TODO add your handling code here:
        String bookId = bookIdText.getText();
        if(bookId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter book ID");
            return;
        }
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("delete from book where bookId='"+bookId+"'");
            JOptionPane.showMessageDialog(null, "Book deleted successfully");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error deleting book: " + e.getMessage());
        }
    }//GEN-LAST:event_bookDeleteActionPerformed

    private void bookUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookUpdateActionPerformed
        // TODO add your handling code here:
        String bookId = bookIdText.getText();
        String bookName = bookNameText.getText();
        String bookAuthor = bookAuthorText.getText();
        String bookYear = bookYearText.getText();
        if(bookId.isEmpty()||bookName.isEmpty()||bookAuthor.isEmpty()||bookYear.isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields must be filled");
            return;
        }
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("update book set bookName='"+bookName+"', bookAuthor='"+bookAuthor+"', bookYear='"+bookYear+"' where bookId='"+bookId+"'");
            JOptionPane.showMessageDialog(null, "Book updated Successfully");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating book");
        }
    }//GEN-LAST:event_bookUpdateActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // TODO add your handling code here:
        String bookId = bookIdText.getText();
        String bookName = bookNameText.getText();
        String bookAuthor = bookAuthorText.getText();
        String bookYear = bookYearText.getText();
        if(bookId.isEmpty()||bookName.isEmpty()||bookAuthor.isEmpty()||bookYear.isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields must be filled");
            return;
        }
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into book values('"+bookId+"','"+bookName+"','"+bookAuthor+"','"+bookYear+"')");
            JOptionPane.showMessageDialog(null, "Books added Successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Book ID already exists");
        }
    }//GEN-LAST:event_addBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String bookId = bookIdText.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from book where bookId='"+bookId+"'");
            if(rs.next()){
                bookNameText.setText(rs.getString(2));
                bookAuthorText.setText(rs.getString(3));
                bookYearText.setText(rs.getString(4));
            }else{
                JOptionPane.showMessageDialog(null, "IncorrectbookId");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "connection error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void memberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberSearchActionPerformed
        // TODO add your handling code here:
        String memberId = memberIdText.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from member where memberId='"+memberId+"'");
            if(rs.next()){
                memberFirstNameText.setText(rs.getString(2));
                memberLastNameText.setText(rs.getString(3));
                addressText.setText(rs.getString(4));
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect memberId");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "connection error");
        }
    }//GEN-LAST:event_memberSearchActionPerformed

    private void memberUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberUpdateActionPerformed
        // TODO add your handling code here:
        String memberId = memberIdText.getText();
        String memberFirstName = memberFirstNameText.getText();
        String memberLastName = memberLastNameText.getText();
        String memberAddress = addressText.getText();
        if(memberId.isEmpty()||memberFirstName.isEmpty()||memberLastName.isEmpty()||memberAddress.isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields must be filled");
            return;
        }
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("update member set memberFirstName='"+memberFirstName+"', memberLastName='"+memberLastName+"', address='"+memberAddress+"' where memberId='"+memberId+"'");
            JOptionPane.showMessageDialog(null, "Member successfully updated");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   
    }//GEN-LAST:event_memberUpdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:  
        String memberId = memberIdText.getText();
        if(memberId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter member ID");
            return;
        }
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("delete from member where memberId='"+memberId+"'");
            JOptionPane.showMessageDialog(null, "Member successfully deleted");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error deleting member: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void memberClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberClearActionPerformed
        // TODO add your handling code here:
        memberIdText.setText("");
        memberFirstNameText.setText("");
        memberLastNameText.setText("");
        addressText.setText("");
    }//GEN-LAST:event_memberClearActionPerformed

    private void clearIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearIssueActionPerformed
        // TODO add your handling code here:
        bookIdText1.setText("");
        memberIdText2.setText("");
        issueDateText.setDate(null);
        dueDateText.setDate(null);
    }//GEN-LAST:event_clearIssueActionPerformed

    private void clearReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearReturnActionPerformed
        // TODO add your handling code here:
        bookIdText3.setText("");
        memberIdText3.setText("");
        issueDateText1.setText("");
        dueDateText1.setText("");
    }//GEN-LAST:event_clearReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new library().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton addMember;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField bookAuthorText;
    private javax.swing.JButton bookDelete;
    private javax.swing.JTextField bookIdText;
    private javax.swing.JTextField bookIdText1;
    private javax.swing.JTextField bookIdText3;
    private javax.swing.JTextField bookNameText;
    private javax.swing.JButton bookUpdate;
    private javax.swing.JTextField bookYearText;
    private javax.swing.JButton clearBook;
    private javax.swing.JButton clearIssue;
    private javax.swing.JButton clearReturn;
    private javax.swing.JLabel dateLabel;
    private com.toedter.calendar.JDateChooser dueDateText;
    private javax.swing.JTextField dueDateText1;
    private javax.swing.JButton issueBookButton;
    private com.toedter.calendar.JDateChooser issueDateText;
    private javax.swing.JTextField issueDateText1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton memberClear;
    private javax.swing.JTextField memberFirstNameText;
    private javax.swing.JTextField memberIdText;
    private javax.swing.JTextField memberIdText2;
    private javax.swing.JTextField memberIdText3;
    private javax.swing.JTextField memberLastNameText;
    private javax.swing.JButton memberSearch;
    private javax.swing.JButton memberUpdate;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
